/// One multiple-choice question generated by the AI Quiz Generator.
class QuizQuestion {
  final String question;
  final List<String> options;
  final int answerIndex;

  const QuizQuestion({
    required this.question,
    required this.options,
    required this.answerIndex,
  });

  /// Builds a question from the JSON that Gemini returns.
  factory QuizQuestion.fromJson(Map<String, dynamic> json) {
    return QuizQuestion(
      question: json['question'] as String,
      options: (json['options'] as List).map((e) => e.toString()).toList(),
      answerIndex: (json['answerIndex'] as num).toInt(),
    );
  }
}
